---
  - hosts: all
    become: true
    tasks:
      - apt:
          pkg: nginx
          state: latest
      - apt:
          pkg: php-fpm
          state: latest
      - apt:
          pkg: php-dom
          state: latest
      - apt:
          pkg: php-zip
          state: latest
      - apt:
          pkg: php-mbstring
          state: latest
      - apt:
          pkg: composer
          state: latest
      - copy:
          src: testapp.conf
          dest: /etc/nginx/sites-available/default
      - git:
          repo: https://github.com/rnurgaliyev/ansible-lab-testapp.git
          dest: /var/www/testapp
      - composer:
          command: install
          working_dir: /var/www/testapp
      - file:
          path: /var/www/testapp/storage
          owner: www-data
          group: www-data
          recurse: yes
      - file:
          path: /var/www/testapp/bootstrap/cache
          owner: www-data
          group: www-data
          recurse: yes
      - copy:
          src: env
          dest: /var/www/testapp/.env
      - service:
          name: nginx
          state: reloaded
